name: e_commerce
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI and UX
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  lottie: ^3.0.0
  flutter_svg: ^2.0.9
  flash: ^3.0.5
  flutter_animate: ^4.5.0
  flutter_staggered_grid_view: ^0.7.0
  smooth_page_indicator: ^1.1.0
  flutter_slidable: ^3.1.0

  # State Management
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.5
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^7.6.4

  # Networking
  dio: ^5.4.0

  # Functional Programming
  fpdart: ^1.1.0

  # Secure Storage
  flutter_secure_storage: ^9.0.0

  # Local Caching
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  bloc_test: ^9.1.5
  mocktail: ^1.0.3


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/lottie/
